name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android@12

      - name: Install Plugins
        run: |
          cordova plugin add cordova-plugin-local-notification
          cordova plugin add cordova-plugin-media
      
      - name: Build APK
        run: cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bharose-wali-ghadi-app
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
